
title: My Resume
url: 'http://bikdroid.github.io'
baseurl: '/bikdroid.github.io' #change it according to your repository name


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6


#Profile information
name: Bikramjit Mandal
tagline: Full Stack Developer
pic: 9660438.jpg  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

#sidebar links
email: edu.bmandal@gmail.com
phone: (469)618-2411
website: www.about.me/mandalb #do not add http://
linkedin: mandalb
github: bikdroid
twitter: '@ghoomanto'

#Update all the sections by editing the files inside _includes folder.
